version: "3.8"
services:
    # Redis Service
    redis:
        image: redis:latest
        container_name: api_redis_server
        ports:
            - "6380:6379"
        volumes:
            - ./redis.conf:/usr/local/etc/redis/redis.conf
            - redis_data:/data
        networks:
            - app_network
        restart: unless-stopped

    # Node.js Server Services
    server:
        container_name: api_node_server
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8080:8080"
        environment:
            - PORT=8080
            - REDIS_HOST=redis
            - REDIS_PORT=6379
        networks:
            - app_network
        volumes:
            - .:/usr/src/app
        depends_on:
            - redis
        restart: unless-stopped

volumes:
    redis_data:

networks:
    app_network:
