version: "3.8"
services:
    redis:
        image: redis:latest
        container_name: api_redis_server
        ports:
            - "6379:6379"
        volumes:
            - redis_data:/data
        networks:
            - redis_network
        restart: unless-stopped

volumes:
    redis_data:

networks:
    redis_network:
