name: Deploy to EC2

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v3

            - name: Install SSH Key
              uses: webfactory/ssh-agent@v0.6.0
              with:
                  ssh-private-key: ${{ secrets.EC2_KEY }}

            - name: Archive Files
              run: tar -czf server.tar.gz .

            - name: Copy Archive to EC2
              run: |
                  scp -o StrictHostKeyChecking=no server.tar.gz ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/home/ubuntu

            - name: Extract Files on EC2
              run: |
                  ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} "mkdir -p /home/ubuntu/server && tar -xzf /home/ubuntu/server.tar.gz -C /home/ubuntu/server"

            - name: Install Dependencies on EC2
              run: |
                  ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} "cd /home/ubuntu/server && npm install"

            - name: Start Application on EC2
              run: |
                  ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} "cd /home/ubuntu/server && npm run start server/src/server.ts"
