name: Deploy to EC2

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            # Step 1: Check out the repository code
            - name: Checkout Repository
              uses: actions/checkout@v3

            # Step 2: Create PEM file from Secret
            - name: Create PEM file
              run: |
                  echo "${{ secrets.EC2_KEY }}" > ec2-key.pem
                  chmod 400 ec2-key.pem

            # Step 3: Deploy to EC2 using SSH
            - name: Deploy to EC2
              run: |
                  ssh -o StrictHostKeyChecking=no -i ec2-key.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
                      if [ ! -d "/var/www/dashboard-server" ]; then
                        sudo mkdir -p /var/www/dashboard-server
                        sudo chown -R $USER:$USER /var/www/dashboard-server
                      fi

                      if [ ! -d "/var/www/dashboard-server/.git" ]; then
                        sudo git clone https://github.com/mitchin20/dashboard-server.git /var/www/dashboard-server
                      else
                        cd /var/www/dashboard-server
                        sudo git pull origin main
                      fi

                      cd /var/www/dashboard-server

                      if [ -d "dist" ]; then
                        sudo rm -rf dist
                      fi
                      
                      sudo rm -rf node_modules package-lock.json
                      sudo npm cache clean --force
                      sudo npm install

                      sudo npm run build

                      if [ ! -f "dist/server.js" ]; then
                        echo "Error: Compiled entry point (dist/server.js) not found."
                        exit 1
                      fi
                      
                      sudo pm2 restart dist/server.js || sudo pm2 start dist/server.js
                  EOF
