name: Deploy to EC2

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            # Step 1: Get GitHub Action IP
            - name: Get GitHub action IP
              id: ip
              uses: haythem/public-ip@v1.2

            # Step 2: Add GitHub Actions IP to Security group
            - name: Add GitHub Actions IP to Security group
              run: |
                  aws ec2 authorize-security-group-ingress --group-name ${{ secrets.AWS_SECURITY_GROUP_NAME }} --protocol tcp --port 22 --cidr ${{ steps.ip.outputs.ipv4 }}/32
              env:
                  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}

            # Step 3: Deploy to EC2 instance
            - name: Deploy to prod server
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.EC2_HOST }}
                  username: ${{ secrets.EC2_USER }}
                  key: ${{ secrets.EC2_KEY }}
                  script: |
                      export NVM_DIR=~/.nvm
                      source ~/.nvm/nvm.sh
                      cd /home/ubuntu/server
                      git stash
                      git pull origin feature/github-action
                      npm install
                      pm2 restart server

            # Step 4: Remove GitHub Actions IP from Security Group after deployment
            - name: Remove GitHub Actions IP from Security group
              run: |
                  aws ec2 revoke-security-group-ingress --group-name ${{ secrets.AWS_SECURITY_GROUP_NAME }} --protocol tcp --port 22 --cidr ${{ steps.ip.outputs.ipv4 }}/32
              env:
                  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
              if: always()
